# -- encoding: utf-8 --
###############################################################################
#
# Copyright (C) 2022-Present Speeduplight (https://speeduplight.com/)
#
###############################################################################
{
    'name': 'Solar Mangment',
    'version': '19.0.1.0.0',
    'sequence': 20,
    'category': 'Product',
    'summary': 'Solar Mangment',
    'description': """
""",
    'author': 'Speeduplight',
    'website': 'https://speeduplight.com/',
    'support': 'contact@speeduplight.com',
    'depends': ['base','crm','mail','portal','project','purchase','sale','sale_crm','stock','account','contacts','maintenance'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/solar_contract_type_data.xml',
        'data/solar_contract_service_data.xml',
        'data/solar_maintenance_data.xml',
        'data/solar_document_type_data.xml',
        'data/ir_cron_data.xml',
        'report/site_inspection_report.xml',
        'report/solar_design_report.xml',
        'views/solar_dashboard_views.xml',
        'views/solar_document_views.xml',
        'views/crm_lead_views.xml',
        'views/solar_design_views.xml',
        'views/solar_government_approval_views.xml',
        'wizards/site_inspection_wizard_views.xml',
        'wizards/site_inspection_reject_wizard_views.xml',
        'wizards/solar_installation_create_wizard_views.xml',
        'views/team_views.xml',
        'views/task_views.xml',
        'views/material_template_views.xml',
        'views/portal_inspection_templates.xml',
        'views/solar_tracking_templates.xml',
        'views/site_inspection_views.xml',
        'views/solar_installation_views.xml',
        'views/project_project_views.xml',
        'views/solar_company_views.xml',
        'views/solar_subcontractor_views.xml',
        'views/sale_order_views.xml',
        'views/solar_contract_views.xml',
        'views/solar_warranty_views.xml',
        'views/document_views.xml',
        'views/solar_alert_views.xml',
        'views/maintenance_request_views.xml',
        'views/solar_energy_billing_views.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sp_solar_management/static/src/css/site_inspection.css',
            'sp_solar_management/static/src/css/solar_dashboard.css',
            'sp_solar_management/static/src/js/solar_dashboard.js',
            'sp_solar_management/static/src/xml/solar_dashboard.xml',
        ],
        'web.assets_frontend': [
            'sp_solar_management/static/src/js/colibri_patch.js',
            'sp_solar_management/static/src/js/portal_home_counters_patch.js',
            'sp_solar_management/static/src/css/portal_inspection.css',
            'sp_solar_management/static/src/css/solar_tracking.css',
            'sp_solar_management/static/src/js/portal_inspection.js',
        ],
    },
    'license': 'OPL-1',
    'price': 199,
    'currency': 'USD',
    'live_test_url': '',
    'images': [
        'static/description/banner.gif',
    ],
    'installable': True,
    'auto_install': True,
    'application': True,
}
